title:              Shenzhen Coder Hustling in Tokyo
email:              john@fongnet.com
description:        A Coder Between Shenzhen and Tokyo | Shenzhen Coder in Tokyo | 东京闯荡的深圳码农 | 東京で奮闘する深圳エンジニア | Engineer from Shenzhen sharing code, tech, and life in Tokyo. | Writing code in Tokyo, shaped by Shenzhen’s tech spirit.
author:             John Fong
baseurl:            "/"
url:                "https://fongnet.com"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   GTM-TPXFQ25H # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
